# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(408, 298)
        Login.setStyleSheet("background-color: white;\n"
"color: black;    \n"
"border: 0px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cred_box = QtWidgets.QGroupBox(Login)
        self.cred_box.setStyleSheet("QLineEdit {\n"
"    background-color: #6498BB;\n"
"    border: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #73A2C1;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #9ABE74;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #A4C482;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #86B37E;\n"
"}")
        self.cred_box.setTitle("")
        self.cred_box.setObjectName("cred_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cred_box)
        self.verticalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.cred_box)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.ejournal = QtWidgets.QGroupBox(self.cred_box)
        self.ejournal.setTitle("")
        self.ejournal.setObjectName("ejournal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ejournal)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.username_ej_box = QtWidgets.QGroupBox(self.ejournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_ej_box.sizePolicy().hasHeightForWidth())
        self.username_ej_box.setSizePolicy(sizePolicy)
        self.username_ej_box.setTitle("")
        self.username_ej_box.setObjectName("username_ej_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.username_ej_box)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_ej_lable = QtWidgets.QLabel(self.username_ej_box)
        self.username_ej_lable.setObjectName("username_ej_lable")
        self.verticalLayout_3.addWidget(self.username_ej_lable)
        self.username_ej = QtWidgets.QLineEdit(self.username_ej_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_ej.sizePolicy().hasHeightForWidth())
        self.username_ej.setSizePolicy(sizePolicy)
        self.username_ej.setMinimumSize(QtCore.QSize(350, 50))
        self.username_ej.setInputMask("")
        self.username_ej.setText("")
        self.username_ej.setMaxLength(32767)
        self.username_ej.setFrame(True)
        self.username_ej.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_ej.setObjectName("username_ej")
        self.verticalLayout_3.addWidget(self.username_ej)
        self.verticalLayout_4.addWidget(self.username_ej_box)
        self.password_ej_box = QtWidgets.QGroupBox(self.ejournal)
        self.password_ej_box.setTitle("")
        self.password_ej_box.setObjectName("password_ej_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.password_ej_box)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.password_lable = QtWidgets.QLabel(self.password_ej_box)
        self.password_lable.setObjectName("password_lable")
        self.verticalLayout_2.addWidget(self.password_lable)
        self.password_ej = QtWidgets.QLineEdit(self.password_ej_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_ej.sizePolicy().hasHeightForWidth())
        self.password_ej.setSizePolicy(sizePolicy)
        self.password_ej.setMinimumSize(QtCore.QSize(350, 50))
        self.password_ej.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_ej.setInputMask("")
        self.password_ej.setText("")
        self.password_ej.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_ej.setObjectName("password_ej")
        self.verticalLayout_2.addWidget(self.password_ej)
        self.verticalLayout_4.addWidget(self.password_ej_box)
        self.verticalLayout_5.addWidget(self.ejournal)
        self.register_btn = QtWidgets.QPushButton(self.cred_box)
        self.register_btn.setMinimumSize(QtCore.QSize(350, 50))
        self.register_btn.setStyleSheet("border: 0px;\n"
"border-radius: 10px;")
        self.register_btn.setObjectName("register_btn")
        self.verticalLayout_5.addWidget(self.register_btn)
        self.verticalLayout.addWidget(self.cred_box)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.label.setText(_translate("Login", "Время сессии журнала закончилась\n"
"Войдите ещё раз"))
        self.username_ej_lable.setText(_translate("Login", "Имя пользователя от elshcool.ru"))
        self.password_lable.setText(_translate("Login", "Пароль от elshcool.ru"))
        self.register_btn.setText(_translate("Login", "Войти"))
