# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 723)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;\n"
"color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border: 0px;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigate_bar = QtWidgets.QGroupBox(self.centralwidget)
        self.navigate_bar.setEnabled(True)
        self.navigate_bar.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(190, 190, 190, 150);\n"
"}")
        self.navigate_bar.setTitle("")
        self.navigate_bar.setObjectName("navigate_bar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.navigate_bar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.back_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setIconSize(QtCore.QSize(50, 50))
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout_3.addWidget(self.back_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.sync_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.sync_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/sync.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sync_btn.setIcon(icon1)
        self.sync_btn.setIconSize(QtCore.QSize(50, 50))
        self.sync_btn.setShortcut("")
        self.sync_btn.setObjectName("sync_btn")
        self.verticalLayout_3.addWidget(self.sync_btn)
        self.user_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.user_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon2)
        self.user_btn.setIconSize(QtCore.QSize(50, 50))
        self.user_btn.setObjectName("user_btn")
        self.verticalLayout_3.addWidget(self.user_btn)
        self.new_task_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.new_task_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/new_task.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_task_btn.setIcon(icon3)
        self.new_task_btn.setIconSize(QtCore.QSize(50, 50))
        self.new_task_btn.setObjectName("new_task_btn")
        self.verticalLayout_3.addWidget(self.new_task_btn)
        self.calendar_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.calendar_btn.setStyleSheet("")
        self.calendar_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar_btn.setIcon(icon4)
        self.calendar_btn.setIconSize(QtCore.QSize(50, 50))
        self.calendar_btn.setObjectName("calendar_btn")
        self.verticalLayout_3.addWidget(self.calendar_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.settings_btn = QtWidgets.QPushButton(self.navigate_bar)
        self.settings_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon5)
        self.settings_btn.setIconSize(QtCore.QSize(50, 50))
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_3.addWidget(self.settings_btn)
        self.horizontalLayout.addWidget(self.navigate_bar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.login = QtWidgets.QWidget()
        self.login.setMaximumSize(QtCore.QSize(16777215, 792))
        self.login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login.setStyleSheet("QListWidget {\n"
"    font-size: 16px;\n"
"}\n"
"QListWidget::item {\n"
"    margin-top: 5px;\n"
"    border-radius: 10px;\n"
"    background: #EDC9FF;\n"
"    height: 70px;\n"
"    color: black;\n"
"}\n"
"QListWidget::item:hover{\n"
"    background: #FED4E7;\n"
"}\n"
"QPushButton#register_btn{\n"
"    color: #0034BB;\n"
"}\n"
"QPushButton#register_btn:hover{\n"
"    color: #0034FF;\n"
"}")
        self.login.setObjectName("login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_list = QtWidgets.QListWidget(self.login)
        self.user_list.setMinimumSize(QtCore.QSize(500, 600))
        self.user_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.user_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.user_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.user_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.user_list.setWordWrap(True)
        self.user_list.setSelectionRectVisible(True)
        self.user_list.setObjectName("user_list")
        self.verticalLayout.addWidget(self.user_list, 0, QtCore.Qt.AlignHCenter)
        self.register_btn = QtWidgets.QPushButton(self.login)
        self.register_btn.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.register_btn.setFont(font)
        self.register_btn.setObjectName("register_btn")
        self.verticalLayout.addWidget(self.register_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.login)
        self.main = QtWidgets.QWidget()
        self.main.setStyleSheet("QListWidget {\n"
"    font-size: 16px;\n"
"}\n"
"QListWidget::item {\n"
"    margin-top: 5px;\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"    background: #EEF5DB;\n"
"    color: black;\n"
"}\n"
"QListWidget::indicator {\n"
"     width: 25px;\n"
"     height: 25px;\n"
" }\n"
"\n"
"QPushButton {\n"
"border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(190, 190, 190, 150);\n"
"}")
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.main)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        self.date_label.setMinimumSize(QtCore.QSize(80, 0))
        self.date_label.setMaximumSize(QtCore.QSize(312, 16777215))
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.archive_btn = QtWidgets.QPushButton(self.groupBox)
        self.archive_btn.setMaximumSize(QtCore.QSize(100, 100))
        self.archive_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/Archive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.archive_btn.setIcon(icon6)
        self.archive_btn.setIconSize(QtCore.QSize(20, 20))
        self.archive_btn.setObjectName("archive_btn")
        self.gridLayout.addWidget(self.archive_btn, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.task_list = QtWidgets.QListWidget(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.task_list.sizePolicy().hasHeightForWidth())
        self.task_list.setSizePolicy(sizePolicy)
        self.task_list.setMinimumSize(QtCore.QSize(500, 0))
        self.task_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.task_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.task_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.task_list.setWordWrap(True)
        self.task_list.setObjectName("task_list")
        self.verticalLayout_2.addWidget(self.task_list, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.main)
        self.calendar = QtWidgets.QWidget()
        self.calendar.setObjectName("calendar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.calendar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendar_widget = QtWidgets.QCalendarWidget(self.calendar)
        self.calendar_widget.setStyleSheet("color: rgb(0, 0, 0);")
        self.calendar_widget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendar_widget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar_widget.setObjectName("calendar_widget")
        self.verticalLayout_4.addWidget(self.calendar_widget)
        self.stackedWidget.addWidget(self.calendar)
        self.settings = QtWidgets.QWidget()
        self.settings.setStyleSheet("QPushButton#delete_btn{\n"
"    background-color: rgb(255, 0, 4);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton#delete_btn:hover{\n"
"    background-color: rgb(255, 8, 103);\n"
"}")
        self.settings.setObjectName("settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.delete_btn = QtWidgets.QPushButton(self.settings)
        self.delete_btn.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("")
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout_5.addWidget(self.delete_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.settings)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.register_btn.setText(_translate("MainWindow", "Добавить нового пользователя"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить"))

    def iterAllItems(self):
        for i in range(self.task_list.count()):
            yield self.task_list.item(i)
