# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("border: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.login = QtWidgets.QWidget()
        self.login.setMaximumSize(QtCore.QSize(16777215, 792))
        self.login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login.setStyleSheet("QListWidget {\n"
"    font-size: 16px;\n"
"    \n"
"}\n"
"QListWidget::item {\n"
"    margin-top: 5px;\n"
"    border-radius: 10px;\n"
"    background: #EDC9FF;\n"
"    height: 70px;\n"
"    color: black;\n"
"}\n"
"QListWidget::item:hover{\n"
"    background: #FED4E7;\n"
"}")
        self.login.setObjectName("login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_list = QtWidgets.QListWidget(self.login)
        self.user_list.setMinimumSize(QtCore.QSize(500, 600))
        self.user_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.user_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.user_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.user_list.setWordWrap(True)
        self.user_list.setSelectionRectVisible(False)
        self.user_list.setObjectName("user_list")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.user_list.addItem(item)
        self.verticalLayout.addWidget(self.user_list, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.login)
        self.main = QtWidgets.QWidget()
        self.main.setStyleSheet("QListWidget {\n"
"    font-size: 16px;\n"
"}\n"
"QListWidget::item {\n"
"    margin-top: 5px;\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"    background: #EEF5DB;\n"
"    color: black;\n"
"}\n"
"QListWidget::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.main)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.user_list.isSortingEnabled()
        self.user_list.setSortingEnabled(False)
        item = self.user_list.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.user_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "ЛитератураПисьменно дать сравнительную характеристику Обломова и Штольца (включить цитаты), дочитать роман до конца. О.Ильинская и А.Пшеницына в жизни LkОбломова"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
