# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_dialog(object):
    def setupUi(self, register_dialog):
        register_dialog.setObjectName("register_dialog")
        register_dialog.resize(408, 433)
        register_dialog.setStyleSheet("background-color: white;\n"
"color: black;    \n"
"border: 0px;")
        register_dialog.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoPredictiveText)
        self.verticalLayout = QtWidgets.QVBoxLayout(register_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.register_label = QtWidgets.QLabel(register_dialog)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.register_label.setFont(font)
        self.register_label.setStyleSheet("")
        self.register_label.setAlignment(QtCore.Qt.AlignCenter)
        self.register_label.setObjectName("register_label")
        self.verticalLayout.addWidget(self.register_label, 0, QtCore.Qt.AlignTop)
        self.cred_box = QtWidgets.QGroupBox(register_dialog)
        self.cred_box.setStyleSheet("QLineEdit {\n"
"    background-color: #6498BB;\n"
"    border: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #73A2C1;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #9ABE74;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #A4C482;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #86B37E;\n"
"}")
        self.cred_box.setTitle("")
        self.cred_box.setObjectName("cred_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cred_box)
        self.verticalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.username_lable = QtWidgets.QLabel(self.cred_box)
        self.username_lable.setObjectName("username_lable")
        self.verticalLayout_5.addWidget(self.username_lable)
        self.username = QtWidgets.QLineEdit(self.cred_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMinimumSize(QtCore.QSize(350, 50))
        self.username.setStyleSheet("")
        self.username.setInputMask("")
        self.username.setText("")
        self.username.setObjectName("username")
        self.verticalLayout_5.addWidget(self.username)
        self.ejournal = QtWidgets.QGroupBox(self.cred_box)
        self.ejournal.setTitle("")
        self.ejournal.setObjectName("ejournal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ejournal)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.username_ej_box = QtWidgets.QGroupBox(self.ejournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_ej_box.sizePolicy().hasHeightForWidth())
        self.username_ej_box.setSizePolicy(sizePolicy)
        self.username_ej_box.setTitle("")
        self.username_ej_box.setObjectName("username_ej_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.username_ej_box)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_ej_lable = QtWidgets.QLabel(self.username_ej_box)
        self.username_ej_lable.setObjectName("username_ej_lable")
        self.verticalLayout_3.addWidget(self.username_ej_lable)
        self.username_ej = QtWidgets.QLineEdit(self.username_ej_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_ej.sizePolicy().hasHeightForWidth())
        self.username_ej.setSizePolicy(sizePolicy)
        self.username_ej.setMinimumSize(QtCore.QSize(350, 50))
        self.username_ej.setInputMask("")
        self.username_ej.setText("")
        self.username_ej.setMaxLength(32767)
        self.username_ej.setFrame(True)
        self.username_ej.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_ej.setObjectName("username_ej")
        self.verticalLayout_3.addWidget(self.username_ej)
        self.verticalLayout_4.addWidget(self.username_ej_box)
        self.password_ej_box = QtWidgets.QGroupBox(self.ejournal)
        self.password_ej_box.setTitle("")
        self.password_ej_box.setObjectName("password_ej_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.password_ej_box)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.password_lable = QtWidgets.QLabel(self.password_ej_box)
        self.password_lable.setObjectName("password_lable")
        self.verticalLayout_2.addWidget(self.password_lable)
        self.password_ej = QtWidgets.QLineEdit(self.password_ej_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_ej.sizePolicy().hasHeightForWidth())
        self.password_ej.setSizePolicy(sizePolicy)
        self.password_ej.setMinimumSize(QtCore.QSize(350, 50))
        self.password_ej.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_ej.setInputMask("")
        self.password_ej.setText("")
        self.password_ej.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_ej.setObjectName("password_ej")
        self.verticalLayout_2.addWidget(self.password_ej)
        self.verticalLayout_4.addWidget(self.password_ej_box)
        self.verticalLayout_5.addWidget(self.ejournal)
        self.register_btn = QtWidgets.QPushButton(self.cred_box)
        self.register_btn.setMinimumSize(QtCore.QSize(350, 50))
        self.register_btn.setStyleSheet("border: 0px;\n"
"border-radius: 10px;")
        self.register_btn.setObjectName("register_btn")
        self.verticalLayout_5.addWidget(self.register_btn)
        self.verticalLayout.addWidget(self.cred_box)

        self.retranslateUi(register_dialog)
        QtCore.QMetaObject.connectSlotsByName(register_dialog)

    def retranslateUi(self, register_dialog):
        _translate = QtCore.QCoreApplication.translate
        register_dialog.setWindowTitle(_translate("register_dialog", "Register"))
        self.register_label.setText(_translate("register_dialog", "Регистрация"))
        self.username_lable.setText(_translate("register_dialog", "*Имя пользователя"))
        self.username_ej_lable.setText(_translate("register_dialog", "Имя пользователя от elshcool.ru"))
        self.password_lable.setText(_translate("register_dialog", "Пароль от elshcool.ru"))
        self.register_btn.setText(_translate("register_dialog", "Создать"))
